### ISSUE TITLE
Can't able to run php screen.php

### ISSUE THREAD

**Issue by Sasi-007** [ikarius6/screen-viewer#1]
C:\xampp\htdocs\Screen-Viewer>php screen.php
PHP Fatal error:  Uncaught Error: Call to undefined function socket_create() in C:\xampp\htdocs\Screen-Viewer\screen.php:8
Stack trace:
#0 {main}
  thrown in C:\xampp\htdocs\Screen-Viewer\screen.php on line 8

Fatal error: Uncaught Error: Call to undefined function socket_create() in C:\xampp\htdocs\Screen-Viewer\screen.php:8
Stack trace:
#0 {main}
  thrown in C:\xampp\htdocs\Screen-Viewer\screen.php on line 8

Is it able to fix this issue??????

**Comment by ikarius6** [comment]
You'll need to install (or enable) the Socket PHP extension: http://www.php.net/manual/en/sockets.installation.php
